In [1]:
using JuMPeR, Mosek, Distributions

In [58]:
#generates some random weights between lv and lv+rng
function genWeightData(numc, numw)
    randn(numw, numc)
end
wd=genWeightData(10, 400)

400x10 Array{Float64,2}:
 -1.62473     0.105063    -0.0234028  …   1.49033     1.47383     1.33363  
  1.88776     0.701751     0.835846       0.512619    0.469131   -1.17615  
 -0.261563   -0.0365803   -1.17822       -0.75471    -1.53489     0.0925674
  2.41607     1.91066      0.443746      -1.14179    -0.301411    2.44146  
  0.115944    0.459139    -1.06758       -0.584539    1.06299    -0.790475 
  0.144107   -1.10848     -0.659711   …  -1.29693    -0.365249    0.41391  
  1.17321     0.123089     0.644203       0.177104   -0.0265702  -0.475053 
 -0.233699    0.427306    -0.480776       0.737427   -0.582324   -0.320118 
 -1.56815    -0.909241     0.382217       1.24056    -0.912435    0.577393 
  1.40695     0.881897     0.950305       1.26945     0.208892   -0.552742 
 -2.38685    -1.03757     -1.65808    …   0.624335   -1.03969    -0.329298 
  1.08237    -0.406856    -0.0935209      0.0282543   1.74356     1.93013  
  0.230246    0.959025     0.975564      -1.56506    -1.25707  

In [6]:
include("src/helpers.jl")

compute_cs (generic function with 1 method)

In [160]:
wd

400x10 Array{Float64,2}:
 -1.62473     0.105063    -0.0234028  …   1.49033     1.47383     1.33363  
  1.88776     0.701751     0.835846       0.512619    0.469131   -1.17615  
 -0.261563   -0.0365803   -1.17822       -0.75471    -1.53489     0.0925674
  2.41607     1.91066      0.443746      -1.14179    -0.301411    2.44146  
  0.115944    0.459139    -1.06758       -0.584539    1.06299    -0.790475 
  0.144107   -1.10848     -0.659711   …  -1.29693    -0.365249    0.41391  
  1.17321     0.123089     0.644203       0.177104   -0.0265702  -0.475053 
 -0.233699    0.427306    -0.480776       0.737427   -0.582324   -0.320118 
 -1.56815    -0.909241     0.382217       1.24056    -0.912435    0.577393 
  1.40695     0.881897     0.950305       1.26945     0.208892   -0.552742 
 -2.38685    -1.03757     -1.65808    …   0.624335   -1.03969    -0.329298 
  1.08237    -0.406856    -0.0935209      0.0282543   1.74356     1.93013  
  0.230246    0.959025     0.975564      -1.56506    -1.25707  

In [14]:
or1 = UDYOracle(wd, 0.1, 0.1)

UDYOracle(0.1,0.09082099531244618,1.7800228310165076,[-0.01533808340820686,-0.04846073845096539,0.026192796915725968,0.04789368555697526,-0.07914668478413006,0.030402019531376664,-0.061888209800156635,0.11397722576919711,0.05761326687052237,0.026648201268432547],10x10 Array{Float64,2}:
  0.953557    -0.0879357    0.0274357   …  -0.0333673   0.0988593   0.0504212
 -0.0879357    1.13758     -0.00567206     -0.0183064  -0.0340708  -0.0265832
  0.0274357   -0.00567206   0.728003        0.118723    0.0291288  -0.0692347
  0.15531      0.0879672    0.00886217     -0.0302159   0.0341074  -0.0213283
  0.0918593    0.064344     0.0250769       0.06961     0.0396338   0.0663108
  0.103637     0.0601088    0.0145757   …  -0.0553338  -0.0280999   0.0289725
  0.00771412  -0.00367933  -0.0465209       0.0494958   0.0736784  -0.0471557
 -0.0333673   -0.0183064    0.118723        0.807227    0.060575   -0.0720189
  0.0988593   -0.0340708    0.0291288       0.060575    1.02019    -0.0234218
  0.0504212

In [24]:
or2 = UMOracle(wd1, 0, 100, 0.1, 0.2)

LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Array{Float64,1}}, ::Int64)
This may have arisen from a call to the constructor Array{Float64,1}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  Array{T}(::Integer)
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{Array{T,1}}, !Matched::Range{T})
  ...
while loading In[24], in expression starting on line 1

In [25]:
capacity=400
cost = 10
m = RobustModel()
setDefaultOracle!(m, or3)
@defVar(m, costs[1:cost] <=100)
# bin var
@defVar(m, -0.5 <= xs[1:cost] <= 1.5, Int)
@defUnc(m, wt[1:cost] <= 1)
@addConstraint(m, sum{wt[i]*xs[i], i=1:cost} <= capacity)
@setObjective(m, Max, sum{costs[i] * xs[i], i=1:cost})

LoadError: LoadError: UndefVarError: or3 not defined
while loading In[25], in expression starting on line 4

In [19]:
solve(m, prefer_cuts= true)

LoadError: LoadError: UDYOracle hasn't implemented registerConstraint
while loading In[19], in expression starting on line 1

In [143]:
using StatsBase

using DataFrames

# load data


#prices = int(open(readdlm,"petcodatafile.txt"))
#squeeze(prices,2)


ebb =readdlm("ebaycsv.csv",',')
# delete first row of label
ebb1 =ebb[1:size(ebb,1) .!= 1,: ]
# attributes

a1 =float64(ebb1[:, 2])
a2 = float64(ebb1[:, 3])
a3 =float64(ebb1[:, 4])

# expd returns , variance
ret= float64(zeros(108));

# calculate 
for i in 2:108
    ret[i] = a1[i]/(a1[i-1]-1) 
end

r = hcat(ret, 12*a2, 12*a3)
#prices = float64(prices)

#rowsize = 108
#colsize = size(prices,2)





# cov
Q= cov(ret)

covar = cov(r)

3x3 Array{Float64,2}:
 0.0224507  0.0354923  0.0425084
 0.0354923  0.322306   0.349733 
 0.0425084  0.349733   0.423159 

In [ ]:
oracle= LCXOracle(sr, 0.2, 0.2)

In [7]:
oracle= UCSOracle(sr, 0.1, 0.1)

LoadError: LoadError: UndefVarError: UCSOracle not defined
while loading In[7], in expression starting on line 1

In [144]:
r

108x3 Array{Float64,2}:
 0.0        0.221628   0.267396
 1.02134   -0.191832   0.02532 
 1.06729    0.137652   0.07854 
 1.05568    0.46146    0.324528
 0.988464   0.439716   0.277476
 1.01965   -0.193404  -0.094872
 1.03913   -0.393144  -0.522444
 1.08599    0.116136  -0.140844
 1.17885    0.471984   0.304356
 0.9495     0.296304   0.208872
 0.955271  -0.6153    -0.919404
 1.02029   -0.07818   -0.131868
 0.835353  -0.759024  -0.540984
 ⋮                             
 0.961538  -0.338676  -0.228876
 1.11365    0.643332   0.649476
 1.01353   -0.14706   -0.061644
 1.02788    0.090876   0.181524
 1.0716     0.097968   0.047472
 0.998012  -0.2544    -0.161724
 0.474679   0.130572  -0.325776
 0.999631  -0.744708  -0.567468
 0.93604   -0.42804   -0.599292
 1.19027    0.870768   0.634152
 1.1        0.002112   0.08796 
 0.961175  -0.294024  -0.43098 

In [145]:
or3= UCSOracle(r, 0.1, 0.1)

DDUS.UCSOracle(0.1,0.16034273643663666,0.27392149386984466,[1.0294856515650634,0.048149555555555536,0.06348655555555553],3x3 Array{Float64,2}:
 0.296372   0.0354923  0.0425084
 0.0354923  0.596227   0.349733 
 0.0425084  0.349733   0.69708  ,3x3 Array{Float64,2}:
 0.544401  0.0651952  0.0780829
 0.0       0.7694     0.447936 
 0.0       0.0        0.700241 ,1.0e-6,Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver is default solver,Empty Array{Variable} (no indices),true,false)

In [ ]:
m = RobustModel()
setDefaultOracle!(m, oracle)

In [156]:

c= covar[1,:] + covar[2,:] + covar[3,:]
sumc = c[1]+ c[2]+ c[3]
@defUnc(m, mu[1:3])
@defVar(m, 0<=t <=100)
@defVar(m, t1 >=0)
@defVar(m, x[1:3] >= 0)
@defVar(m, sum1[1:3] )
@defVar(m, 1 <= lambda <=10)

#@defVar(m, q[1:3] == x*covar[1,:]*x + x*covar[2,:]*x + x*covar[3,:]*x)
@addConstraint(m, sum(sum1)== sumc)
@addConstraint(m, sum(x) == 1)
@addConstraint(m, sum{-mu[i] * x[i], i=1:3}+ lambda*sumc <=t)


@setObjective(m, Min, t)

t

In [159]:
solve(m, prefer_cuts=true)
println("Obj Value:\t", getObjectiveValue(m))
println("Portfolio:\t", getValue(x))
println("lambda:\t", getValue(lambda))
println("uncert set:\t", getValue(mu))


Obj Value:	2.486539196973916
Portfolio:	[1.0,0.0,0.0]
lambda:	1.0


LoadError: LoadError: MethodError: `getValue` has no method matching getValue(::JuMPeR.Uncertain)
while loading In[159], in expression starting on line 5

In [76]:
include("examples/AmbiguitySets-master/src/chiSqVar.jl")

chiSqVarCov (generic function with 1 method)

In [31]:
include("examples/AmbiguitySets-master/src/asymptotics.jl")

cov_const (generic function with 1 method)

In [32]:
include("examples/AmbiguitySets-master/src/klVar.jl")

mult_bracket (generic function with 1 method)

In [33]:
include("examples/AmbiguitySets-master/src/DirRes.jl")


Use "[]" instead.


Dir

In [55]:
css = ChiSqSet(wd, 0.1)

Size:	0.4373454978131813


ChiSqSet(200x10 Array{Float64,2}:
  0.0127659   -0.0307405   -0.0572956   …  -0.0418294   -0.0615148 
  0.00563728  -0.101579     0.021633       -0.0290175   -0.0470471 
 -0.0254356    0.0492752    0.0178872       0.0204641   -0.105046  
  0.0901175    0.0502285   -0.0114307      -0.0392994   -0.0389917 
  0.0822558   -0.0968459    0.0825312      -0.0351711    0.0984397 
 -0.0187951   -0.102503     0.0753357   …   0.00610007  -0.0452045 
 -0.0313323    0.0365546    0.0550202       0.0316502   -0.0436429 
 -0.0452628   -0.0508075    0.0102195       0.0289209    0.0102243 
 -0.153169    -0.0577669   -0.057861       -0.0846369    0.0243971 
  0.0437374    0.0174943   -0.0352643      -0.0639202    0.0614043 
 -0.0218832    0.00560413   0.00774536  …  -0.0349149   -0.0780628 
 -0.0380533    0.0275314    0.0375179       0.108889    -0.0870365 
 -0.0123362   -0.0063881   -0.0238964       0.0181941   -0.0160378 
  ⋮                                     ⋱                          
  0.0196463   

In [59]:
capacity=400
cost = 10
m = RobustModel()
setDefaultOracle!(m, css)
@defVar(m, costs[1:cost] <=100)
@defVar(m, t>=0)
# bin var
@defVar(m, -0.5 <= xs[1:cost] <= 1.5, Int)
@defUnc(m, wt[1:cost] <= 1)
@addConstraint(m, sum{costs[i] * xs[i], i=1:cost}>=t)
@addConstraint(m, sum{wt[i]*xs[i], i=1:cost} <= capacity)
@setObjective(m, Max, t)

t

In [60]:
solve(m, prefer_cuts=true)

LoadError: LoadError: ChiSqSet hasn't implemented registerConstraint
while loading In[60], in expression starting on line 1

In [46]:
orc = UChiSquaredOracle(wd, 0.1, 0.1)

LoadError: LoadError: UndefVarError: UChiSquaredOracle not defined
while loading In[46], in expression starting on line 1

In [51]:
include("examples/UIIDMOracle.jl")

setup (generic function with 18 methods)